# =============================================================================
# Forge — Inventory
# Prototype topology: 1 physical host + 2 KVM guests
#
# remote-workstation  → localhost (the physical box via 127.0.0.1)
# dev-workstation     → KVM guest  (SSH via 127.0.0.1:2222 after provisioning)
# forge-infra         → KVM guest  (SSH via 127.0.0.1:2223 after provisioning)
# =============================================================================

all:
  vars:
    ansible_user: forge                        # default non-root user inside VMs
    ansible_become: true

  hosts:
    # ── physical host ──────────────────────────────────────────────────────
    remote-workstation:
      ansible_connection: local
      ansible_user: oyon
      ansible_become: true
      ansible_python_interpreter: /usr/bin/python3.13

  children:
    # ── KVM guests (reachable only AFTER kvm role has provisioned them) ────
    vm_guests:
      hosts:
        dev-workstation:
          ansible_host: 127.0.0.1
          ansible_port: 2222
          ansible_user: forge
          ansible_become: true
          ansible_ssh_private_key_file: "{{ forge_ssh_key }}"

        forge-infra:
          ansible_host: 127.0.0.1
          ansible_port: 2223
          ansible_user: forge
          ansible_become: true
          ansible_ssh_private_key_file: "{{ forge_ssh_key }}"
